### ISSUE TITLE
Generality

### ISSUE THREAD

**Issue by jm-begon** [montefiore-ai/image_datasets#2]
It is not clear whether this repo is general purpose or if it was meant to be used with a given framework (Keras, PyTorch, etc.).

I think PyTorch (through torchvision) has a built-in system for that need: https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder

**Comment by waliens** [comment]
I think all modern frameworks have their own data loading components so this one is not meant to be used alongside another framework. 

This lib is an alternative when you don't work with PyTorch or Keras (or whatever) but you still want to load a dataset. It provides basic functionnalities with minimal requirements and dependencies.  

I will make that clearer in the README !
